<a href="https://colab.research.google.com/github/ranikanhe/project-with-Python-Assignment/blob/main/8_Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Array Inspection and Creation - Programming Questions

Array Inspection:

1.	Write a Python program to create a NumPy array from a list and print its shape.
o	List = [1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np
List = [1, 2, 3, 4, 5, 6]

a = np.array(List)
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


2.	Write a Python program to create a NumPy array and print its number of dimensions (ndim).
o	Array = [[1,2,3],[4,5,6]]


In [ ]:
import numpy as np

Array = [[1,2,3],[4,5,6]]
b = np.array(Array)
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


3.	Write a Python program to create a NumPy array and print its total number of elements (size).
o	Array = [10, 20, 30, 40, 50]


In [ ]:
import numpy as np
Array = [10, 20, 30, 40, 50]

c = np.array(Array)
print(c)
print(c.size)

[10 20 30 40 50]
5


4.	Write a Python program to find the data type (dtype) of a given NumPy array.
o	Array = [1.0, 2.5, 3.8]


In [ ]:
import numpy as np

Array = [1.0, 2.5, 3.8]

d = np.array(Array)
print(d.dtype)


float64


5.	Write a Python program to convert the data type of a NumPy array from float to int using astype().
o	Array = [5.5, 6.7, 8.9]


In [ ]:
import numpy as np

Array = [5.5, 6.7, 8.9]
e = np.array(Array,dtype = int)
e.astype(int)
print(e)
print(e.dtype)


[5 6 8]
int64


Different Ways of Creating Arrays:

6.	Write a Python program to create a NumPy array initialized with all zeros of size 4.

In [ ]:
import numpy as np
a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


7.	Write a Python program to create a NumPy array initialized with all ones of size (2,3).

In [ ]:
import numpy as np
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


8.	Write a Python program to create a NumPy array containing numbers from 10 to 30 (excluding 30) using np.arange().

In [ ]:
import numpy as np
a = np.arange(10,30)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


9.	Write a Python program to create a NumPy array of 7 random integers between 0 and 100.

In [ ]:
import numpy as np

a = np.random.randint(0,100,7)
print(a)

[87 73 32 58 48 78 77]


10.	Write a Python program to create an array with 10 numbers evenly spaced between 0 and 5 using linspace().

In [ ]:
import numpy as np

a = np.linspace(0,5,10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


11.	Write a Python program to create a NumPy array directly from the numbers [11, 22, 33, 44, 55].

In [ ]:
import numpy as np
a = np.array([11, 22, 33, 44, 55])
print(a)

[11 22 33 44 55]


12.	Write a Python program to create a 1D NumPy array from a given Python list.
o	List = [3, 6, 9, 12, 15]


In [ ]:
import numpy as np
a = np.array([3, 6, 9, 12, 15])
print(a)


[ 3  6  9 12 15]


13.	Write a Python program to create a 2D NumPy array from a tuple.
o	Tuple = ((1,2,3),(4,5,6))


In [ ]:
import numpy as np
a = np.array(((1,2,3),(4,5,6)))
print(a)
a.ndim

[[1 2 3]
 [4 5 6]]


2

14.	Write a Python program to create a 3x3 identity matrix using NumPy.

In [ ]:
import numpy as np
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


15.	Write a Python program to create a 5x5 array initialized with random floats between 0 and 1.

In [ ]:
import numpy as np
a = np.random.rand(5,5)
print(a)

[[0.99667391 0.64631473 0.23074519 0.36188591 0.19473535]
 [0.62315889 0.70769556 0.47473109 0.27406218 0.11717644]
 [0.00511051 0.64093735 0.81631136 0.14766743 0.28781164]
 [0.14587943 0.4359013  0.14160788 0.81325197 0.72791754]
 [0.02222668 0.55214442 0.17654102 0.34321796 0.79728341]]
